name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    strategy:
      fail-fast: false
      matrix:
        php_tag: [ "8.0", "8.2", "8.3", "8.4" ]
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Define image names
        id: names
        run: |
          echo "ghcr=ghcr.io/bilyboy785/php-apache-nextcloud" >> $GITHUB_OUTPUT
          echo "dh=docker.io/martinbouillaud/php-apache-nextcloud" >> $GITHUB_OUTPUT

      - name: Docker metadata (only php-<version> tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.names.outputs.ghcr }}
            ${{ steps.names.outputs.dh }}
          tags: |
            type=raw,value=php-${{ matrix.php_tag }}

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_TAG=${{ matrix.php_tag }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Build Docker image
      #   run: |
      #     docker buildx create --use
      #     docker buildx build --platform linux/amd64,linux/arm64 \
      #       -t ${{ secrets.DOCKERHUB_USERNAME }}/php-apache-nextcloud:${GITHUB_REF_NAME} \
      #       -t ghcr.io/${{ secrets.GHCR_USERNAME }}/php-apache-nextcloud:${GITHUB_REF_NAME} \
      #       --push .

      # - name: Push to Docker Hub
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/php-apache-nextcloud:${GITHUB_REF_NAME}

      # - name: Push to GHCR
      #   run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/php-apache-nextcloud:${GITHUB_REF_NAME}