name: Build image

on:
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/php-apache-nextcloud:test \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/php-apache-nextcloud:test \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            --push .