name: Trivy Security Scan

on:
  push:
    tags:
      - '*'
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/**
      - deploy.sh

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (local, pas de push)
        run: |
          docker buildx build --load -t php-apache-nextcloud .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.33.0
        with:
          image-ref: php-apache-nextcloud
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
